#!/bin/bash

# Clone repository
git clone https://github.com/RiyadAhsan4516/hapijs-typescript-boilerplate.git

# Check if the cloning was successful
if [ $? -eq 0 ]; then
  echo "Repository cloned successfully."
  
  # Prompt user for a new folder name
      echo "// ********************************************
// *                                          *
// *         SET PROJECT NAME	              *
// *                                          *
// ********************************************"
  read -p "What should be the name of your project? (press Enter to keep the default): " new_folder_name
  
  # Set the new folder name or keep the default
  if [ -z "$new_folder_name" ]; then
    folder_name="Hapijs-Project"
  else
    folder_name="$new_folder_name"
  fi

  # Rename the cloned folder
  mv hapijs-typescript-boilerplate "$folder_name"

  # Remove .git directory from the cloned folder
  rm -rf "$folder_name/.git"

  cd "$folder_name"

  # Ask for user confirmation
  read -p "Do you want to proceed with the installation? (y/n): " proceed

  # Check user's response
  if [[ "$proceed" == "y" || "$proceed" == "Y" || "$proceed" == "" ]]; then
    # Run yarn install
    yarn install
    
    # Check if yarn install was successful
    if [ $? -eq 0 ]; then
      echo "Yarn install completed successfully."
      echo
      
      # Create .env file with user-input fields
      echo "// ********************************************
// *                                          *
// *         CREATE .env FILE	              *
// *                                          *
// ********************************************"
      
      echo "Please enter the values for the fields in .env file:"
      read -p "NODE_ENV: " field1_value
      read -p "PORT: " field2_value
      read -p "LOCALHOST: " field3_value
      read -p "DB_USER: " field4_value
      read -s -p "DB_PASSWORD: " field5_value
      echo
      read -p "DB_LOCAL: " field6_value
      
      echo "NODE_ENV=$field1_value" > .env
      echo "PORT=$field2_value" >> .env
      echo "LOCALHOST=$field3_value" >> .env
      echo "DB_USER=$field4_value" >> .env
      echo "DB_PASSWORD=$field5_value" >> .env
      echo "DB_LOCAL=$field6_value" >> .env
      
      echo "// ********************************************
// *                                          *
// *         .env FILE CREATED	              *
// *                                          *
// ********************************************"
	  
	  echo
	  
      echo "Project set up complete"
    else
      echo "Failed to run yarn install."
    fi
  else
    echo "Installation canceled please install it manually."
  fi
else
  echo "Failed to clone the repository."
fi

#chmod +x hapiscript.sh (give write permission to the script)
